---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "HUSH-777 "
    reviewers:
      - "r-bk"
  - package-ecosystem: "pip"
    directories:
      - "/cli"
      - "/tests"
    schedule:
      interval: "monthly"
    groups:
      all-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "HUSH-777 "
    reviewers:
      - "r-bk"
