apiVersion: am.hush.security/v1alpha1
kind: AccessCredential
metadata:
  name: demo-postgres-cr
spec:
  name: demo-postgres-cr
  type: postgres
  description: Metoraf
  config:
    db_name: electric
    host: mdev-postgres.c7ikykg627kq.eu-central-1.rds.amazonaws.com
    port: 5432
    ssl_mode: prefer
    username: mdev_postgres
  secretRef:
    name: demo-postgres
