apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hush-common.fullName" . }}
  labels: {{- include "hush-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway-cluster-role
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    resourceNames: ["kube-system"]
    verbs: ["get"]
