apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hush-common.fullName" . }}
  labels: {{- include "hush-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway-service-account
  namespace: {{ include "hush-common.namespace" . }}
  {{- with .Values.agw.serviceAccount.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
