---
apiController:
  apiKey:
    secretKeyRef:
      name: "pre-existing-api-key-secret"
      idKey: "api-key-id"
      secretKey: "api-key-secret"

secretStore:
  kind: "awssm"
  aws:
    region: "eu-central-1"
