---
hushDeployment:
  token: "ZDE6em9uZTpyZWFsbTpvcmctaWQ6ZGVwbG95bWVudC1pZA=="
  password: "koko.password"

admissionController:
  failurePolicy: "Fail"
  objectSelector:
    type: "labels"
    labels:
      am.hush.security/admission: "true"
