{{- if and .Values.apiController.enabled .Values.apiController.apiKey.id .Values.apiController.apiKey.secret -}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "hush-am.apiControllerFullName" . }}-api-key
  labels: {{- include "hush-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-controller-api-key-secret
  namespace: {{ include "hush-common.namespace" . }}
data:
  api-key-id: {{ .Values.apiController.apiKey.id | b64enc }}
  api-key-secret: {{ .Values.apiController.apiKey.secret | b64enc }}
{{- end }}
