{{- if .Values.apiController.enabled -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hush-am.apiControllerFullName" . }}
  labels: {{- include "hush-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-controller-service-account
  namespace: {{ include "hush-common.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-controller-role-binding
  namespace: {{ include "hush-common.namespace" . }}
  labels: {{- include "hush-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-controller-role-binding
subjects:
- kind: ServiceAccount
  name: {{ include "hush-am.apiControllerFullName" . }}
  namespace: {{ include "hush-common.namespace" . }}
roleRef:
  kind: Role
  name: {{ include "hush-am.apiControllerFullName" . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hush-am.apiControllerFullName" . }}
  labels: {{- include "hush-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-controller-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: {{ include "hush-am.apiControllerFullName" . }}
  namespace: {{ include "hush-common.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "hush-am.apiControllerFullName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
