{{- if .Values.apiController.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hush-am.apiControllerFullName" . }}
  labels: {{- include "hush-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-controller
  namespace: {{ include "hush-common.namespace" . }}
spec:
  selector:
    matchLabels: {{- include "hush-common.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api-controller
  replicas: {{ .Values.apiController.replicas }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels: {{- include "hush-common.labels" . | nindent 8 }}
        app.kubernetes.io/component: api-controller
    spec:
      restartPolicy: Always
      {{- with (include "hush-am.kubeImagePullSecretEffectiveList" .) }}
      imagePullSecrets: {{- . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hush-am.apiControllerFullName" . }}
      initContainers:
        - name: api-controller-init
          image: {{ include "hush-am.apiControllerImagePath" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: data-volume
              mountPath: {{ include "hush-am.dataVolumeMountPath" . }}
          command: ["/bin/sh", "-c"]
          args:
            - mkdir -p {{ include "hush-am.apiControllerDataDirPath" . }}
      containers:
        - name: api-controller
          image: {{ include "hush-am.apiControllerImagePath" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.apiController.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data-volume
              mountPath: {{ include "hush-am.dataVolumeMountPath" . }}
            - name: vector-socket-dir
              mountPath: /tmp/vector
            - name: {{ include "hush-common.k8sSecretsProjectionVolumeName" . }}
              mountPath: {{ include "hush-common.k8sSecretsProjectionVolumePath" . }}
              readOnly: true
          env:
            {{- include "hush-am.apiControllerEnvs" . | nindent 12 }}
        - name: vector
          image: {{ include "hush-am.accessManagerVectorImagePath" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.apiController.vectorResources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: vector-socket-dir
              mountPath: /tmp/vector
            - name: {{ include "hush-common.k8sSecretsProjectionVolumeName" . }}
              mountPath: {{ include "hush-common.k8sSecretsProjectionVolumePath" . }}
              readOnly: true
          env:
            {{- include "hush-am.mandatoryEnvs" . | nindent 12 }}
            {{- with (include "hush-am.effectiveDeploymentPasswordKubeSecretRef" . | fromYaml) }}
            - name: DEPLOYMENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .name }}
                  key: {{ .key }}
            {{- end }}
            - name: REPORT_SUBSYSTEM_NAME
              value: "api-controller"
            - name: REPORT_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HELM_RELEASE
              value: {{ .Release.Name }}
            - name: HELM_NAMESPACE
              value: {{ include "hush-common.namespace" . }}
            - name: HELM_CHART_VERSION
              value: {{ .Chart.Version | quote }}
      volumes:
        - name: data-volume
          emptyDir: {}
        - name: vector-socket-dir
          emptyDir:
            sizeLimit: 1Mi
        - name: {{ include "hush-common.k8sSecretsProjectionVolumeName" . }}
          projected:
            sources:
              - serviceAccountToken:
                  path: {{ include "hush-common.k8sSaTokenFileName" . }}
{{- end }}
