---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hush-am.clusterRoleFullName" . }}
  labels: {{- include "hush-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: cluster-role
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - nodes
      - nodes/proxy
    verbs:
      - get
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - watch
---
# Separate from the common ClusterRole, which is also bound to spire-agent.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hush-am.accessManagerFullName" . }}-webhook-publisher-cluster-role
  labels: {{- include "hush-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: access-manager-webhook-publisher-cluster-role
rules:
  - apiGroups: ["admissionregistration.k8s.io"]
    resources:
      - mutatingwebhookconfigurations
    resourceNames:
      - {{ include "hush-am.mutatingWebhookFullName" . }}
    verbs:
      - patch
{{- if (include "hush-am.secretWriteNamespaces" .) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hush-am.accessManagerFullName" . }}-secret-writer-cluster-role
  labels: {{- include "hush-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: access-manager-secret-writer-cluster-role
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs: ["*"]
{{- end }}
