{{- if .Values.diagnostics.enabled -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "hush-am.diagFullName" . }}-lease
  labels: {{- include "hush-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: diag-role
  namespace: {{ include "hush-common.namespace" . }}
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources:
      - leases
    resourceNames:
      - hush-am-diag-healthcheck
    verbs:
      - get
      - update
  - apiGroups: ["coordination.k8s.io"]
    resources:
      - leases
    verbs:
      - create
  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
      - daemonsets
    verbs:
      - get
      - list
{{- end }}
