{{/*
Deployment K8S Secret name
*/}}
{{- define "hush-common.deploymentKubeSecretName" -}}
{{- printf "%s-deploymentsecret" (include "hush-common.fullName" .) }}
{{- end }}

{{/*
Verify hushDeployment.token was defined
*/}}
{{- define "hush-common.getDeploymentTokenValue" -}}
{{- $token := and .Values.hushDeployment .Values.hushDeployment.token -}}
{{- if not $token -}}
    {{- fail "'hushDeployment.token' is undefined" -}}
{{- end -}}
{{- printf "%s" $token -}}
{{- end }}

{{/*
Should we create the deployment token K8S Secret?
*/}}
{{- define "hush-common.shouldCreateDeploymentTokenKubeSecret" -}}
{{- $keyRef := and .Values.hushDeployment .Values.hushDeployment.secretKeyRef -}}
{{- $name := and $keyRef $keyRef.name -}}
{{- $tokenKey := and $keyRef $keyRef.tokenKey -}}
{{- if not (and $name $tokenKey) -}}
true
{{- end }}
{{- end }}

{{/*
Should we create the deployment password K8S Secret?
*/}}
{{- define "hush-common.shouldCreateDeploymentPasswordKubeSecret" -}}
{{- $keyRef := and .Values.hushDeployment .Values.hushDeployment.secretKeyRef -}}
{{- $name := and $keyRef $keyRef.name -}}
{{- $key := and $keyRef $keyRef.key -}}
{{- if not (and $name $key) -}}
true
{{- end }}
{{- end }}

{{/*
Should we create deployment K8S Secret?
*/}}
{{- define "hush-common.shouldCreateDeploymentKubeSecret" -}}
{{- if or
    (include "hush-common.shouldCreateDeploymentTokenKubeSecret" .)
    (include "hush-common.shouldCreateDeploymentPasswordKubeSecret" .) -}}
true
{{- end -}}
{{- end }}

{{/*
Effective deployment token secret ref
*/}}
{{- define "hush-common.effectiveDeploymentTokenKubeSecretRef" -}}
{{- if (include "hush-common.shouldCreateDeploymentTokenKubeSecret" .) -}}
    {{- dict
        "name" (include "hush-common.deploymentKubeSecretName" .)
        "key" "deployment-token"
        | toYaml
    -}}
{{- else -}}
    {{- dict
        "name" .Values.hushDeployment.secretKeyRef.name
        "key" .Values.hushDeployment.secretKeyRef.tokenKey
        | toYaml
    -}}
{{- end }}
{{- end }}

{{/*
Effective deployment password secret ref
*/}}
{{- define "hush-common.effectiveDeploymentPasswordKubeSecretRef" -}}
{{- if (include "hush-common.shouldCreateDeploymentKubeSecret" .) -}}
    {{- dict
        "name" (include "hush-common.deploymentKubeSecretName" .)
        "key" "deployment-password"
        | toYaml
    -}}
{{- else -}}
    {{- dict
        "name" .Values.hushDeployment.secretKeyRef.name
        "key" .Values.hushDeployment.secretKeyRef.key
        | toYaml
    -}}
{{- end }}
{{- end }}
