{{- if .Values.connector.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hush-sensor.connectorFullName" . }}
  labels: {{- include "hush-sensor.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "hush-sensor.connectorFullName" . }}
    namespace: {{ include "hush-sensor.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "hush-sensor.connectorFullName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
