{{- if .Values.connector.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hush-sensor.connectorFullName" . }}
  labels: {{- include "hush-sensor.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get"]
{{- end }}
