{{- if include "hush-sensor.shouldCreateDaemonSet" . -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "hush-sensor.fullName" . }}
  labels: {{- include "hush-sensor.labels" . | nindent 4 }}
  namespace: {{ include "hush-sensor.namespace" . }}

spec:
  selector:
    matchLabels: {{- include "hush-sensor.selectorLabels" . | nindent 6 }}
  {{- with .Values.daemonSet.updateStrategy }}
  updateStrategy: {{- toYaml . | nindent 4 }}
  {{- end }}

  template:
    metadata:
      labels: {{- include "hush-sensor.labels" . | nindent 8 }}
      {{ with (include "hush-sensor.daemonSetAnnotations" .) -}}
      annotations: {{- . | nindent 8 }}
      {{- end }}

    spec:
      {{- with .Values.daemonSet.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.daemonSet.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.daemonSet.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.daemonSet.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      {{- with (include "hush-sensor.kubeImagePullSecretEffectiveList" .) }}
      imagePullSecrets: {{- . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.daemonSet.terminationGracePeriodSeconds }}
      serviceAccountName: {{ include "hush-sensor.fullName" . }}
      volumes:
        - name: cri
          hostPath:
            path: {{ include "hush-sensor.criMountPath" . }}
            type: Directory
        - name: cgroupfs
          hostPath:
            path: /sys/fs/cgroup
            type: Directory
        - name: vector-socket
          emptyDir:
            sizeLimit: 1Mi
        - name: sensor-config
          configMap:
            name: {{ include "hush-sensor.sensorConfigMapName" . }}
            items:
              - key: sensor_config
                path: config.yaml
        - name: host-dir
          hostPath:
            path: {{ .Values.hostDir }}
            type: DirectoryOrCreate
        {{- with and .Values.daemonSet .Values.daemonSet.extraVolumes -}}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
        - name: hush-sensor
          image: {{ include "hush-sensor.sensorImagePath" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with and .Values.daemonSet .Values.daemonSet.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            privileged: true
            seccompProfile:
              type: Unconfined
            {{- with (include "hush-sensor.appArmorProfile" .) }}
            appArmorProfile:
              {{- . | nindent 14 }}
            {{- end }}
          volumeMounts:
            - name: vector-socket
              mountPath: /tmp/vector
            - name: cri
              mountPath: {{ include "hush-sensor.criMountPath" . }}
              readOnly: true
            - name: cgroupfs
              mountPath: /hostcgroup
              readOnly: true
            - name: sensor-config
              mountPath: /opt/snoopy/config/
              readOnly: true
            - name: host-dir
              mountPath: /var/lib/hush-security
            {{- with and .Values.daemonSet .Values.daemonSet.sensorExtraVolumeMounts -}}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            - name: SELF_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- with (include "hush-sensor.effectiveDeploymentTokenKubeSecretRef" . | fromYaml) }}
            - name: DEPLOYMENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .name }}
                  key: {{ .key }}
            {{- end }}
            {{- with (include "hush-sensor.effectiveDeploymentPasswordKubeSecretRef" . | fromYaml) }}
            - name: DEPLOYMENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .name }}
                  key: {{ .key }}
            {{- end }}
            - name: DEPLOYMENT_KIND
              value: k8s
            {{- with (and .Values.daemonSet .Values.daemonSet.workloadSampling) -}}
              {{- if .amountThreshold }}
            - name: IDENTITY_SAMPLING_AMOUNT_THRESHOLD
              value: {{ .amountThreshold | quote }}
              {{- end }}
              {{- if .timeThreshold }}
            - name: IDENTITY_SAMPLING_TIME_THRESHOLD
              value: {{ .timeThreshold | quote}}
              {{- end }}
            {{- end }}
        - name: hush-sensor-vector
          image: {{ include "hush-sensor.sensorVectorImagePath" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with and .Values.daemonSet .Values.daemonSet.vectorResources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: vector-socket
              mountPath: /tmp/vector
            - name: host-dir
              mountPath: /var/lib/hush-security
              readOnly: true
          env:
            {{- with (include "hush-sensor.effectiveDeploymentTokenKubeSecretRef" . | fromYaml) }}
            - name: DEPLOYMENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .name }}
                  key: {{ .key }}
            {{- end }}
            {{- with (include "hush-sensor.effectiveDeploymentPasswordKubeSecretRef" . | fromYaml) }}
            - name: DEPLOYMENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .name }}
                  key: {{ .key }}
            {{- end }}
            - name: DEPLOYMENT_KIND
              value: k8s
            - name: REPORT_HOST_METRICS
              value: "1"
            - name: REPORT_APP_METRICS
              value: "1"
            - name: AGENT_ID_PATH
              value: "/var/lib/hush-security/sensor_uuid"
            - name: REPORT_SUBSYSTEM_NAME
              value: "snoopy"
            - name: REPORT_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            {{- if .Values.eventReportingConsole }}
            - name: EVENT_REPORTING_CONSOLE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "hush-sensor.sensorConfigMapName" . }}
                  key: event_reporting_console
            {{- end }}
            - name: HELM_RELEASE
              value: {{ .Release.Name }}
            - name: HELM_NAMESPACE
              value: {{ include "hush-sensor.namespace" . }}
            - name: HELM_CHART_VERSION
              value: {{ .Chart.Version | quote }}
{{- end -}}
