{{- if include "hush-sensor.shouldCreateDaemonSet" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hush-sensor.fullName" . }}
  labels: {{- include "hush-sensor.labels" . | nindent 4 }}
  namespace: {{ include "hush-sensor.namespace" . }}
{{- end }}
