{{- if include "hush-sensor.shouldCreateDaemonSet" . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hush-sensor.fullName" . }}
  labels: {{- include "hush-sensor.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
{{- end }}
