apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "hush-sensor.fullName" . }}
  labels: {{- include "hush-sensor.labels" . | nindent 4 }}
  namespace: {{ include "hush-sensor.namespace" . }}

spec:
  selector:
    matchLabels: {{- include "hush-sensor.selectorLabels" . | nindent 6 }}
  {{- with .Values.daemonSet.updateStrategy }}
  updateStrategy: {{- toYaml . | nindent 4 }}
  {{- end }}

  template:
    metadata:
      labels: {{- include "hush-sensor.labels" . | nindent 8 }}
      {{ with (include "hush-sensor.daemonSetAnnotations" .) -}}
      annotations: {{- . | nindent 8 }}
      {{- end }}

    spec:
      {{- with .Values.daemonSet.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.daemonSet.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.daemonSet.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.daemonSet.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      {{- with (include "hush-sensor.imagePullSecretEffectiveList" .) }}
      imagePullSecrets: {{- . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.daemonSet.terminationGracePeriodSeconds }}
      volumes:
        - name: cri
          hostPath:
            path: {{ include "hush-sensor.criMountPath" . }}
            type: Directory
        - name: cgroupfs
          hostPath:
            path: /sys/fs/cgroup
            type: Directory
        - name: vector-socket
          emptyDir:
            sizeLimit: 1Mi
        - name: sensor-config
          configMap:
            name: {{ include "hush-sensor.sensorConfigMapName" . }}
            items:
              - key: sensor_config
                path: config.yaml
        {{- with and .Values.daemonSet .Values.daemonSet.extraVolumes -}}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
        - name: hush-sensor
          image: {{ include "hush-sensor.sensorImagePath" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true
            seccompProfile:
              type: Unconfined
            {{- with (include "hush-sensor.appArmorProfile" .) }}
            appArmorProfile:
              {{- . | nindent 14 }}
            {{- end }}
          volumeMounts:
            - name: vector-socket
              mountPath: /tmp/vector
            - name: cri
              mountPath: {{ include "hush-sensor.criMountPath" . }}
              readOnly: true
            - name: cgroupfs
              mountPath: /hostcgroup
              readOnly: true
            - name: sensor-config
              mountPath: /opt/snoopy/config/
              readOnly: true
            {{- with and .Values.daemonSet .Values.daemonSet.sensorExtraVolumeMounts -}}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            - name: SELF_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
        - name: hush-sensor-vector
          image: {{ include "hush-sensor.sensorVectorImagePath" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: vector-socket
              mountPath: /tmp/vector
          env:
            - name: EVENT_REPORTING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "hush-sensor.sensorConfigMapName" . }}
                  key: event_reporting_uri
            - name: EVENT_REPORTING_ORG_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "hush-sensor.sensorConfigMapName" . }}
                  key: org_id
            - name: EVENT_REPORTING_DEPLOYMENT_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "hush-sensor.sensorConfigMapName" . }}
                  key: deployment_id
            {{- with (include "hush-sensor.effectiveDeploymentPasswordSecretRef" . | fromYaml) }}
            - name: EVENT_REPORTING_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .name }}
                  key: {{ .key }}
            {{- end }}
