{{- if (include "hush-sensor.shouldCreateDeploymentKubeSecret" .) -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "hush-common.deploymentKubeSecretName" . }}
  labels: {{- include "hush-common.labels" . | nindent 4 }}
  namespace: {{ include "hush-common.namespace" . }}
data:
  {{- if (include "hush-sensor.shouldCreateDeploymentTokenKubeSecret" .) }}
  deployment-token: {{ (include "hush-sensor.getDeploymentTokenValue" .) | b64enc }}
  {{- end }}
  {{- if (include "hush-sensor.shouldCreateDeploymentPasswordKubeSecret" .) }}
  deployment-password: {{ (include "hush-sensor.getDeploymentPasswordValue" .) | b64enc }}
  {{- end }}
{{- end }}
