{{- if (include "hush-sensor.shouldCreateDeploymentSecret" .) -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "hush-sensor.deploymentSecretName" . }}
  labels: {{- include "hush-sensor.labels" . | nindent 4 }}
  namespace: {{ include "hush-sensor.namespace" . }}
data:
  {{- if (include "hush-sensor.shouldCreateDeploymentTokenSecret" .) }}
  deployment-token: {{ (include "hush-sensor.getDeploymentTokenValue" .) | b64enc }}
  {{- end }}
  {{- if (include "hush-sensor.shouldCreateDeploymentPasswordSecret" .) }}
  deployment-password: {{ (include "hush-sensor.getDeploymentPasswordValue" .) | b64enc }}
  {{- end }}
{{- end }}
