{{- if (include "hush-sensor.shouldCreateDeploymentSecret" .) -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "hush-sensor.deploymentSecretName" . }}
  labels: {{- include "hush-sensor.labels" . | nindent 4 }}
  namespace: {{ include "hush-sensor.namespace" . }}
data:
  deployment-password: {{ (include "hush-sensor.getDeploymentPassword" .) | b64enc }}
{{- end }}
