apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "hush-sensor.deploymentSecretName" . }}
  labels: {{- include "hush-sensor.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace.name }}
data:
  deployment-token: {{ (include "hush-sensor.getDeploymentToken" .) | b64enc }}
