{{- if (include "hush-sensor.shouldCreateKubeImagePullSecret" .) -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ include "hush-sensor.kubeImagePullSecretName" . }}
  labels: {{- include "hush-sensor.labels" . | nindent 4 }}
  namespace: {{ include "hush-sensor.namespace" . }}
data:
  .dockerconfigjson: {{ include "hush-sensor.kubeImagePullSecretData" . | quote }}
{{- end -}}
