{{- if (include "hush-sensor.shouldCreateImagePullSecret" .) -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ include "hush-sensor.imagePullSecretName" . }}
  labels: {{- include "hush-sensor.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace.name }}
data:
  .dockerconfigjson: {{ include "hush-sensor.imagePullSecretValue" . | quote }}
{{- end -}}
