apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hush-sensor.sensorConfigMapName" . }}
  labels: {{- include "hush-sensor.labels" . | nindent 4 }}
  namespace: {{ include "hush-sensor.namespace" . }}
data:
  sensor_config: |
    trace_pods_default: {{ .Values.sensorConfigMap.trace_pods_default }}
    report_tls: {{ .Values.sensorConfigMap.report_tls }}
    self_k8s_namespace: {{ include "hush-sensor.namespace" . | quote }}
    {{- with (include "hush-sensor.criSocketPath" .) }}
    cri_socket_path: {{ . | quote }}
    {{- end }}
    {{- with .Values.sensorConfigMap.akeyless_gateway_domain }}
    akeyless_gateway_domain: {{ . | quote }}
    {{- end }}
  event_reporting_console: {{ .Values.eventReportingConsole | quote }}
  sentry_config: |
    trace_pods_default: {{ .Values.sensorConfigMap.trace_pods_default }}
    self_k8s_namespace: {{ include "hush-sensor.namespace" . | quote }}
    integrations:
    {{- with (include "hush-sensor.sentryAwsIntegrations" .) }}
    {{- . | nindent 6 -}}
    {{- end }}
    {{- with (include "hush-sensor.sentryK8SIntegrations" .) }}
    {{- . | nindent 6 -}}
    {{- end }}
