apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hush-sensor.sensorConfigMapName" . }}
  labels: {{- include "hush-sensor.labels" . | nindent 4 }}
  namespace: {{ include "hush-sensor.namespace" . }}
data:
  sensor_config: |
    trace_pods_default: {{ .Values.sensorConfigMap.trace_pods_default }}
    report_tls: {{ .Values.sensorConfigMap.report_tls }}
    self_k8s_namespace: {{ include "hush-sensor.namespace" . | quote }}
    {{- with (include "hush-sensor.criSocketPath" .) }}
    cri_socket_path: {{ . | quote }}
    {{- end }}
    {{- with .Values.sensorConfigMap.akeyless_gateway_domain }}
    akeyless_gateway_domain: {{ . | quote }}
    {{- end }}
  event_reporting_console: {{ .Values.eventReportingConsole | quote }}
  sentry_config: |
    trace_pods_default: {{ .Values.sensorConfigMap.trace_pods_default }}
    self_k8s_namespace: {{ include "hush-sensor.namespace" . | quote }}
    {{- with .Values.sentry.integrations }}
    integrations:
    {{- if and .aws (or .aws.irsa  .aws.assume_role_arn) }}
      aws:
        enabled: true
        {{- if and .aws.assume_role_arn (not .aws.irsa) }}
        assume_role_arn: {{ .aws.assume_role_arn | quote }}
        {{- end }}
    {{- end }}
    {{- end }}
