{{- if .Values.sentry.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hush-sensor.sentryFullName" . }}
  labels: {{- include "hush-sensor.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "hush-sensor.sentryFullName" . }}
  namespace: {{ include "hush-sensor.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "hush-sensor.sentryFullName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
