{{- if .Values.sentry.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hush-sensor.sentryFullName" . }}
  labels: {{- include "hush-sensor.labels" . | nindent 4 }}
  namespace: {{ include "hush-sensor.namespace" . }}
  {{ with and .Values.sentry.serviceAccount .Values.sentry.serviceAccount.annotations -}}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
