{{- if .Values.sentry.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hush-sensor.sentryFullName" . }}
  labels: {{- include "hush-sensor.labels" . | nindent 4 }}
  namespace: {{ include "hush-sensor.namespace" . }}
  {{- with (include "hush-sensor.sentryServiceAccountAnnotations" .) }}
  annotations: {{- . | nindent 4 }}
  {{- end }}
{{- end }}
