{{- if .Values.vermon.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hush-sensor.vermonFullName" . }}
  labels: {{- include "hush-sensor.labels" . | nindent 4 }}
  namespace: {{ include "hush-sensor.namespace" . }}
{{- end -}}
