---
hushDeployment:
  token: "ZDE6em9uZTpyZWFsbTpvcmctaWQ6ZGVwbG95bWVudC1pZA=="
  password: "koko.password"

sentry:
  integrations:
    hc_vault:
      server: "https://vault.svc:8200"
      vaultCACert:
        secretKeyRef:
          name: "vault-tls"
          key: "ca.crt"
      auth:
        k8s:
          role: "myrole"
