---
hushDeployment:
  token: "ZDE6em9uZTpyZWFsbTpvcmctaWQ6ZGVwbG95bWVudC1pZA=="
  password: "koko.password"

sentry:
  integrations:
    akeyless:
      base_url: "https://akeyless-gw.akeyless.svc:8000/api/v2"
      caCert:
        secretKeyRef:
          name: "akeyless-gw-tls"
          key: "ca.crt"
      auth:
        api_key:
          access_id: "p-abc123"
          accessKey:
            secretKeyRef:
              name: "akeyless-api-key"
              key: "access-key"
