apiVersion: v2
name: hush-sensor
description: A Helm chart for Hush Security sensor.
type: application
version: 0.28.0
home: https://hush.security
dependencies:
  - name: hush-common
    version: 0.1.0
    repository: "file://./charts/hush-common"
