# Default values for hush-sensor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This is to override the chart name.
nameOverride: ""

# This is to override the chart fullname.
fullnameOverride: ""

# Labels applied to all resources.
# For more information see
# https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
commonLabels: {}

# The namespace for everything hush
namespace:
  create: true
  name: "hush-security"

deploymentToken: ""

# Values related to container images
image:
  # Image pull token contains registry information and credentials
  pullToken: ""

  # Container registry to pull images from
  #
  # This value is ignored when 'image.pullToken' is defined.
  registry: hushsecurity.azurecr.io

  # Overrides the image tag.
  tag: "v1"

  # A list of pre-created image pull secrets of the form:
  #
  # pullSecretList:
  #   - name: "<secret-name-here>"
  #
  # Secrets must be pre-created in namespace specified in 'namespace.name'.
  #
  # When this list is empty 'image.pullSecret' can be used to create a secret
  # automatically.
  #
  # More information can be found here:
  # https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  pullSecretList: []

  # Creates a Secret for pulling images
  #
  # When 'image.pullToken' is defined the credentials for the Secret are taken
  # from there. Otherwise both 'username' and 'password' must be defined.
  #
  # When 'image.pullSecretList' is non-empty the created secret is not used.
  pullSecret:
    # Custom pull secret name.
    # When not defined chart's full name is used with '-imagepullsecret' suffix.
    name: ""
    # Pull secret username
    #
    # This value is ignored when 'image.pullToken' is defined.
    username: ""
    # Pull secret password
    #
    # This value is ignored when 'image.pullToken' is defined.
    password: ""

  # The pull policy for images.
  pullPolicy: Always

  # The repository used for sensor
  sensorRepository: sensor

  # The repository used for sensor-vector
  vectorRepository: sensor-vector

daemonSet:
  # Custom priority class
  priorityClassName: ""

  # Custom node selector
  nodeSelector: {}

  # A custom CRI socket path.
  #
  # This must be the full socket path on the Host.
  # Needed in cases when it cannot be auto-detected.
  criSocketPath: ""

  # Additional annotations.
  # For more information see
  # https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  annotations: {}

  # Termination grace period
  terminationGracePeriodSeconds: 30

  # An update strategy
  updateStrategy:
    type: RollingUpdate

  # Node affinity.
  # Choose the node types by OS and Arch.
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
                - linux
            - key: kubernetes.io/arch
              operator: In
              values:
                - amd64
                - arm64

  # A list of tolerations.
  # For more information see
  # https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
  tolerations: []

  # An additional set of volumes
  extraVolumes: []

  # An additional set of mounts for sensor
  sensorExtraVolumeMounts: []

sensorConfigMap:
  # Configure pod tracing:
  #   false = trace annotated pods only
  #   true  = trace all pods (besides kube-system)
  trace_pods_default: true
  # Report TLS connections
  report_tls: false
