---
name: Release
on:
  push:
    branches:
      - "**-ci"
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Install Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install poetry
        uses: Gr1N/setup-poetry@v9
      - name: GPG test
        run: gpg --version
